In [1]:
import pandas as pd
import numpy as np
import gdown

In [2]:
file_id = '1juE8Rbc08p35Bsscq28rPZhFGg8aIFcu'

url = f'https://drive.google.com/uc?id={file_id}'

gdown.download(url, 'hr_data.csv', quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1juE8Rbc08p35Bsscq28rPZhFGg8aIFcu
To: C:\Users\Etebom\Documents\RGN\Projects\Sprints\SP_2\HR_Dataset\files\hr_data.csv
100%|██████████████████████████████████████████████████████████████████████████████| 73.6k/73.6k [00:00<00:00, 192kB/s]

'hr_data.csv'

In [3]:
#Read file into a dataframe
hr = pd.read_csv('hr_data.csv')

#View the first few rows of the hr dataframe
hr.head()

,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,grace,25,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,NaN
1,david,NaN,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,hannah,35,SIXTY THOUSAND,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,eve,NaN,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,grace,NaN,NAN,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321

In [3]:
#View a summary of the hr dataframe
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               1000 non-null   object
 1   Age                841 non-null    object
 2   Salary             1000 non-null   object
 3   Gender             1000 non-null   object
 4   Department         1000 non-null   object
 5   Position           1000 non-null   object
 6   Joining Date       1000 non-null   object
 7   Performance Score  1000 non-null   object
 8   Email              610 non-null    object
 9   Phone Number       815 non-null    object
dtypes: object(10)
memory usage: 78.3+ KB

### VIEW UNIQUE ITEMS IN EACH COLUMN IN ORDER TO GUIDE DATA CLEANING ACTIONS

In [4]:
hr['Age'].unique()

array(['25', nan, '35', '40', 'thirty', '50'], dtype=object)

In [5]:
hr['Salary'].unique()

array(['50000', '65000', 'SIXTY THOUSAND', ' NAN ', '70000', '55000'],
      dtype=object)

In [6]:
hr['Gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [7]:
hr['Department'].unique()

array(['HR', 'Finance', 'Sales', 'IT', 'Marketing'], dtype=object)

In [8]:
hr['Position'].unique()

array(['Manager', 'Director', 'Clerk', 'Assistant', 'Analyst'],
      dtype=object)

In [9]:
hr['Joining Date'].unique()

array(['April 5, 2018', '2020/02/20', '01/15/2020', '03-25-2019',
       '2019.12.01'], dtype=object)

In [10]:
hr['Performance Score'].unique()

array(['D', 'F', 'C', 'A', 'B'], dtype=object)

In [11]:
hr['Email'].unique()

array(['email@example.com', 'user@domain.com', 'name@company.org', nan],
      dtype=object)

In [12]:
hr['Phone Number'].unique()

array([nan, '123-456-7890', '098-765-4321', ' ', '555-555-5555'],
      dtype=object)

### CREATE A FUNCTION TO PERFORM BASIC DATA CLEANING FOR THE HR DATAFRAME

In [13]:
#Function definition
def wrangle(df):
    #Remove all trailing spaces in the 'Name' column
    df['Name'] = df['Name'].str.strip()
    
    #Replace 'thirty' with '30' in the 'Age' column
    df['Age'] = df['Age'].replace({'thirty':'30'})
    
    #Replace 'SIXTY THOUSAND' with '60000' in the 'Salary' column
    df['Salary'] = df['Salary'].replace({'SIXTY THOUSAND':'60000'})

    #Unify the date format in 'Joining Date' column
    df['Joining Date'] = pd.to_datetime(df['Joining Date'], format='mixed')
    df['Joining Date'] = df['Joining Date'].dt.strftime('%Y-%m-%d')
    
    #Convert 'Age' and 'Salary' columns data type from 'object' to 'int'
    df[['Age', 'Salary']] = df[['Age', 'Salary']].replace({' NAN ': '0'})
    df[['Age', 'Salary']] = df[['Age', 'Salary']].fillna('0')
    df[['Age', 'Salary']] = df[['Age', 'Salary']].astype('int')
    
    return df

In [14]:
#Use the wrangle function to clean the hr dataframe
wrangle(hr)
hr.head()

,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,grace,25,50000,Male,HR,Manager,2018-04-05,D,email@example.com,NaN
1,david,0,65000,Female,Finance,Director,2020-02-20,F,user@domain.com,123-456-7890
2,hannah,35,60000,Female,Sales,Director,2020-01-15,C,email@example.com,098-765-4321
3,eve,0,50000,Female,IT,Manager,2018-04-05,A,name@company.org,
4,grace,0,0,Female,Finance,Manager,2020-01-15,F,name@company.org,098-765-4321

#### HANDLE MISSING VALUES IN THE AGE COLUMN

In [15]:
#Get a count of values in the Age column
hr.Age.value_counts()

Age
30    176
25    171
40    170
35    163
50    161
0     159
Name: count, dtype: int64

In [16]:
#Get indices of zero(missing) values
zero_indices = hr[hr['Age'] == 0].index

#Shuffle the indices
shuffled_indices = np.random.permutation(zero_indices)

#Calculate allocation counts
n_total = len(shuffled_indices)

n_each = int(n_total * 0.2)
n_30 = n_each
n_25 = n_each
n_40 = n_each
n_35 = n_each
n_50 = n_total - (n_30 + n_25 + n_40 + n_35)

#Assign values to shuffled indices
hr.loc[shuffled_indices[:n_30], 'Age'] = 30
hr.loc[shuffled_indices[n_30:n_30 + n_25], 'Age'] = 25
hr.loc[shuffled_indices[n_30 + n_25:n_30 + n_25 + n_40], 'Age'] = 40
hr.loc[shuffled_indices[n_30 + n_25 + n_40:n_30 + n_25 + n_40 + n_35], 'Age'] = 35
hr.loc[shuffled_indices[n_30 + n_25 + n_40 + n_35:], 'Age'] = 50

In [17]:
hr['Age'].value_counts()

Age
30    207
25    202
40    201
50    196
35    194
Name: count, dtype: int64

#### HANDLE MISSING VALUES IN THE SALARY COLUMN

In [18]:
#Get a count of values in the Age column
hr.Salary.value_counts()

Salary
65000    184
70000    173
55000    172
0        167
50000    161
60000    143
Name: count, dtype: int64

In [19]:
#Get indices of zero values
zero_indices = hr[hr['Salary'] == 0].index

#Shuffle the indices
shuffled_indices = np.random.permutation(zero_indices)

#Calculate allocation counts
n_total = len(shuffled_indices)

n_each = int(n_total * 0.2)  
n_65 = n_each
n_70 = n_each
n_55 = n_each
n_50 = n_each
n_60 = n_total - (n_65 + n_70 + n_55 + n_50)  

#Assign values to shuffled indices
hr.loc[shuffled_indices[:n_65], 'Salary'] = 65000
hr.loc[shuffled_indices[n_65:n_65 + n_70], 'Salary'] = 70000
hr.loc[shuffled_indices[n_65 + n_70:n_65 + n_70 + n_55], 'Salary'] = 55000
hr.loc[shuffled_indices[n_65 + n_70 + n_55:n_65 + n_70 + n_55 + n_50], 'Salary'] = 50000
hr.loc[shuffled_indices[n_65 + n_70 + n_55 + n_50:], 'Salary'] = 60000

In [20]:
hr.Salary.value_counts()

Salary
65000    217
70000    206
55000    205
50000    194
60000    178
Name: count, dtype: int64

### CHECK FOR OTHER MISSING VALUES AND HANDLE THEM

In [21]:
hr.isnull().any()

Name                 False
Age                  False
Salary               False
Gender               False
Department           False
Position             False
Joining Date         False
Performance Score    False
Email                 True
Phone Number          True
dtype: bool

In [22]:
hr['Email'] = hr.Email.fillna('missing')

In [23]:
hr['Phone Number'] = hr['Phone Number'].fillna('missing')
hr['Phone Number'] = hr['Phone Number'].replace({' ':'missing'})

In [24]:
hr['Phone Number'].value_counts()

Phone Number
missing         376
123-456-7890    236
098-765-4321    199
555-555-5555    189
Name: count, dtype: int64

In [25]:
hr.isnull().any()

Name                 False
Age                  False
Salary               False
Gender               False
Department           False
Position             False
Joining Date         False
Performance Score    False
Email                False
Phone Number         False
dtype: bool

### A SNAPSHOT OF THE CLEANED DATAFRAME

In [26]:
hr.head()

,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,grace,25,50000,Male,HR,Manager,2018-04-05,D,email@example.com,missing
1,david,35,65000,Female,Finance,Director,2020-02-20,F,user@domain.com,123-456-7890
2,hannah,35,60000,Female,Sales,Director,2020-01-15,C,email@example.com,098-765-4321
3,eve,50,50000,Female,IT,Manager,2018-04-05,A,name@company.org,missing
4,grace,50,65000,Female,Finance,Manager,2020-01-15,F,name@company.org,098-765-4321